services:
  dev-db:
    image: postgres:latest
    ports:
      - "${DB_DEV_PORTS}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - harbor_network

  test-db:
    image: postgres:latest
    ports:
      - "${DB_TEST_PORTS}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - harbor_network

networks:
  harbor_network:
