services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: harbor_admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: harbor_db
    networks:
      - harbor_network
  test-db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: harbor_admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: harbor_db
    networks:
      - harbor_network
networks:
  harbor_network:
