const emojiOptions = [
  { label: "Heart ❤️", value: "❤️" },
  { label: "Star ⭐", value: "⭐" },
  { label: "Fire 🔥", value: "🔥" },
  { label: "Thumbs Up 👍", value: "👍" },
  { label: "Clap 👏", value: "👏" },
  { label: "Pray 🙏", value: "🙏" },
  { label: "Rocket 🚀", value: "🚀" },
  { label: "Trophy 🏆", value: "🏆" },
  { label: "Checkmark ✅", value: "✅" },
  { label: "Light Bulb 💡", value: "💡" },
  { label: "Diamond 💎", value: "💎" },
  { label: "Money 💰", value: "💰" },
  { label: "Chart 📈", value: "📈" },
  { label: "Target 🎯", value: "🎯" },
  { label: "Bell 🔔", value: "🔔" },
  { label: "Anchor ⚓", value: "⚓" },
  { label: "Shield 🛡️", value: "🛡️" },
  { label: "Sword ⚔️", value: "⚔️" },
  { label: "Key 🔑", value: "🔑" },
  { label: "Lock 🔒", value: "🔒" },
  { label: "Medal 🏅", value: "🏅" },
  { label: "Crown 👑", value: "👑" },
  { label: "Coffee ☕", value: "☕" },
  { label: "Pizza 🍕", value: "🍕" },
  { label: "Burger 🍔", value: "🍔" },
  { label: "Taco 🌮", value: "🌮" },
  { label: "Beer 🍺", value: "🍺" },
  { label: "Wine 🍷", value: "🍷" },
  { label: "Champagne 🥂", value: "🥂" },
  { label: "Cake 🎂", value: "🎂" },
  { label: "Candy 🍬", value: "🍬" },
  { label: "Lollipop 🍭", value: "🍭" },
  { label: "Gift 🎁", value: "🎁" },
  { label: "Balloon 🎈", value: "🎈" },
  { label: "Music 🎵", value: "🎵" },
  { label: "Headphones 🎧", value: "🎧" },
  { label: "Microphone 🎤", value: "🎤" },
  { label: "Film 🎬", value: "🎬" },
  { label: "Camera 📷", value: "📷" },
  { label: "TV 📺", value: "📺" },
  { label: "Laptop 💻", value: "💻" },
  { label: "Phone 📱", value: "📱" },
  { label: "Game Controller 🎮", value: "🎮" },
  { label: "Basketball 🏀", value: "🏀" },
  { label: "Soccer ⚽", value: "⚽" },
  { label: "Baseball ⚾", value: "⚾" },
  { label: "Tennis 🎾", value: "🎾" },
  { label: "Football 🏈", value: "🏈" },
  { label: "Chess ♟️", value: "♟️" },
  { label: "Globe 🌍", value: "🌍" },
  { label: "Tree 🌲", value: "🌲" },
  { label: "Flower 🌸", value: "🌸" },
  { label: "Sun 🌞", value: "🌞" },
  { label: "Cloud ☁️", value: "☁️" },
  { label: "Rain 🌧️", value: "🌧️" },
  { label: "Snowflake ❄️", value: "❄️" },
  { label: "Moon 🌙", value: "🌙" },
  { label: "Mountain ⛰️", value: "⛰️" },
  { label: "Car 🚗", value: "🚗" },
  { label: "Airplane ✈️", value: "✈️" },
  { label: "Train 🚆", value: "🚆" },
  { label: "Bicycle 🚲", value: "🚲" },
  { label: "Boat 🚤", value: "🚤" },
  { label: "Umbrella ☂️", value: "☂️" },
  { label: "Clock ⏰", value: "⏰" },
  { label: "Pencil ✏️", value: "✏️" },
  { label: "Scissors ✂️", value: "✂️" },
  { label: "Paint 🎨", value: "🎨" },
  { label: "Hammer 🔨", value: "🔨" },
  { label: "Wrench 🔧", value: "🔧" },
  { label: "Mail 📧", value: "📧" },
  { label: "Brain 🧠", value: "🧠" },
  { label: "Book 📚", value: "📚" },
  { label: "Magnifying Glass 🔍", value: "🔍" },
  { label: "Paperclip 📎", value: "📎" },
  { label: "Shopping Bag 🛍️", value: "🛍️" },
  { label: "Tools 🛠️", value: "🛠️" },
  { label: "Tent ⛺", value: "⛺" },
  { label: "Lantern 🏮", value: "🏮" },
  { label: "Flag 🚩", value: "🚩" },
  { label: "Web 🌐", value: "🌐" },
];

export default emojiOptions;
